Ruby on Rails/lab3/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  resources :books
  resources :users 
end

Ruby on Rails/lab3/app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true, length: {minimum:3}
  validates :price, presence: true
  validates :image,presence: true
  validates :description,presence: true
  belongs_to :user
end

Ruby on Rails/lab3/app/models/user.rb
class User < ApplicationRecord
end

Ruby on Rails/lab3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Ruby on Rails/lab3/app/controllers/books_controller.rb
class BooksController < ApplicationController
  http_basic_authenticate_with name: "nada", password: "123456", except: [:index, :show]
  def index
    @books=Book.all
  end

  def show
    @book= Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create 
    @book=Book.new(book_params)
    @book.user_id = User.find_by(name: authenticated_username).id
    @book.image = save_image(params[:book][:image])
    p @book
    if @book.save
      redirect_to book_path(@book)
    else 
      render :new, status: :unprocessable_entity 
    end
  end

  def edit 
    @book= Book.find(params[:id])
  end

  def update
    @book= Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else 
      render :edit,status: :unprocessable_entity
    end 
  end

  def destroy
    @book= Book.find(params[:id])
    @book.destroy
    redirect_to root_path ,status: :see_other
  end

  private
  def save_image(image)
    timestamp = Time.now.strftime("%Y%m%d%H%M%S")
    extension = File.extname(image.original_filename).downcase
    filename = "#{timestamp}_#{SecureRandom.hex(8)}#{extension}"
    filepath = Rails.root.join('public', 'images', filename)

    File.open(filepath, 'wb') do |file|
      file.write(image.read)
    end

    filename
  end

  private
  def authenticated_username
    username, _password = ActionController::HttpAuthentication::Basic::user_name_and_password(request)
    username
  end

  private
  def book_params
    params.require(:book).permit(:name, :image ,:price, :description )
  end
end

Ruby on Rails/lab3/app/helpers/books_helper.rb
module BooksHelper
end

Ruby on Rails/lab3/app/views/books/_form.html.erb
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }

    input[type="text"],
    input[type="file"] {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    .error-message {
        color: red;
        margin-top: 5px;
    }

    .submit-button {
        display: block;
        width: 100%;
        padding: 8px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
</style>

<%= form_with model: book do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <% @book.errors.full_messages_for(:name).each do |message| %>
        <div class="error-message"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.text_field :price %>
        <% @book.errors.full_messages_for(:price).each do |message| %>
        <div class="error-message"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>
    <div>
        <%= form.label  :image %>
        <%= form.file_field :image, class: "form-control" %>
        <% book.errors.full_messages_for(:image).each do |message| %>
            <div class="error-message"> <%= message %> </div>
        <% end %>
    </div>
    <div>
        <%= form.submit "Submit", class: "submit-button" %>
    </div>
<% end %>

Ruby on Rails/lab3/app/views/books/edit.html.erb
<h1>Edit <h1>
<%= render "form" ,book: @book %> 

Ruby on Rails/lab3/app/views/books/index.html.erb
<style>
    h1 {
        color: #333;
        font-size: 24px;
        margin-bottom: 20px;
    }

    .table {
        margin: 20px auto;
        width: 100%;
        border-collapse: collapse;
    }

    th,
    td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ccc;
    }

    th {
        background-color: #f2f2f2;
        font-weight: bold;
    }

    .btn {
        display: inline-block;
        padding: 6px 12px;
        font-size: 14px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        white-space: nowrap;
        cursor: pointer;
        border: none;
        border-radius: 4px;
        color: #fff;
    }

    .btn-primary {
        background-color: #007bff;
    }

    .btn-success {
        background-color: #28a745;
    }

    .btn-danger {
        background-color: #dc3545;
    }
</style>

<h1>Books</h1>
<%= link_to "Create New Book", new_book_path, class: "btn btn-primary" %>
<table class="table">
    <thead>
        <tr>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">Price</th>
        <th scope="col">Created At</th>
        <th>Updated At</th>
        <th>Action</th>
        <th>Created By</th>
        </tr>
    </thead>

    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= book.name %></td>
            <td><%= book.image %></td>
            <td><%= book.price %></td>
            <td><%= book.created_at %></td>
            <td><%= book.updated_at %></td>
            <td><%= book.user.name %></td>
            <td>
                <a href="<%= book_path(book) %>" class="btn btn-primary">Show</a>
                <a href="<%= edit_book_path(book) %>" class="btn btn-success">Update</a>
                <a class="btn btn-danger"
                <%= link_to "Delete", book_path(book), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %> 
                </a>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

Ruby on Rails/lab3/app/views/books/new.html.erb
<h1> New Book </h1>

<%= render "form" ,book: @book %>

<%= link_to "Back" , root_path(@book) %> 

Ruby on Rails/lab3/app/views/books/show.html.erb
<style>
  .card {
    width: 40rem;
    margin: 0 auto;
    margin-top: 20px;
    border: 1px solid rgba(0, 0, 0, 0.125);
    border-radius: 0.25rem;
    box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
  }

  .card-body {
    display: flex;
    flex-direction: row;
  }

  .card-img {
    flex: 0 0 auto;
    margin-right: 10px;
    max-width: 250px;
  }

  .card-content {
    flex: 1 1 auto;
  }

  .card-title {
    font-size: 1.25rem;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .card-text {
    margin-bottom: 20px;
  }

  .card-link {
    margin-right: 10px;
  }
  

  .btn {
    display: inline-block;
    padding: 8px 12px;
    border-radius: 4px;
    margin-right: 10px;
    text-decoration: none;
    color: #fff;
    font-weight: bold;
    cursor: pointer;
  }

  .btn-primary {
    background-color: #007bff;
    border-color: #007bff;
  }

  .btn-danger {
    background-color: #dc3545;
    border-color: #dc3545;
  }

  .btn-secondary {
    background-color: #6c757d;
    border-color: #6c757d;
  }
</style>

<div class="card">
  <div class="card-body">
    <% if @book.image.present? %>
      <%= image_tag("/images/" + @book.image, class: "card-img") %>
    <% end %>
    <div class="card-content">
      <h5 class="card-title"><%= @book.name %></h5>
      <p class="card-text"><%= @book.description %></p>
      <%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary card-link" %>
      <%= link_to "Destroy", book_path(@book), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      }, class: "btn btn-danger card-link" %>
      <%= link_to "Back", root_path, class: "btn btn-secondary card-link" %>
    </div>
  </div>
</div>

Ruby on Rails/lab3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>