django/djangoLabs/bookStore/urls.py
from django.urls import path
from .views import *

app_name = 'bookStore'

urlpatterns = [
    path('', index, name="index"),
    path('details/<int:book_id>', show_details, name="show_details"),
    path('edit/<int:id>', edit_book, name="edit"),
    path('delete/<int:id>', delete_book , name="delete"),
    path('add/', add_book , name="add"),
]

django/djangoLabs/djangoLabs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookStore/', include('bookStore.urls')),
    path("user/" , include('user.urls') , name="user")
]

django/djangoLabs/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login" , views.user_login , name="login"),
    path("logout" , views.user_logout , name="logout"),
    path("signup" , views.user_signup , name="signup"),
]

django/djangoLabs/bookStore/models.py
from django.db import models

class Book(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places= 3)
    description = models.TextField()
    author_name = models.CharField(max_length=20)
    pages = models.IntegerField(max_length=50)

    def __str__(self):
        return self.name

django/djangoLabs/user/models.py
from django.db import models

# Create your models here.

django/djangoLabs/bookStore/forms.py
from django.forms import TextInput, NumberInput
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'author_name', 'pages', 'price']
        widgets = {
            'name': TextInput(attrs={
                'class': "form-control w-100",
                'placeholder': 'Name'
                }),
            'description': TextInput(attrs={
                'class': "form-control w-100", 
                'placeholder': 'Description'
                }),
            'author_name': TextInput(attrs={
                'class': "form-control w-100", 
                'placeholder': 'Author Name'
                }), 
            'pages': NumberInput(attrs={
                'class': "form-control w-100",
                'placeholder': 'Pages'
                }),   
            'price': NumberInput(attrs={
                'class': "form-control w-100", 
                'placeholder': 'Price'
                }),    
        }

django/djangoLabs/user/forms.py
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})),

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username' , 'first_name' , 'last_name' , 'email']

django/djangoLabs/bookStore/views.py
from django.shortcuts import render, redirect
from .models import Book
from .forms import BookForm
from django.contrib.auth.decorators import login_required

book_list = Book.objects.all()

@login_required(login_url='/user/login')
def index(request):
    my_context = {'book_list': Book.objects.all()}
    return render(request, 'index.html', context=my_context)

@login_required(login_url='/user/login')
def add_book(request):
    form = BookForm()
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bookStore:index')
    return render(request, 'create-book.html', context={'form': form})

@login_required(login_url='/user/login')
def show_details(request, *args, **kwrgs):
    book_id = kwrgs.get('book_id')
    book = Book.objects.get(id=book_id)
    my_context = {'book': book}
    return render(request, "book-details.html",context=my_context)

@login_required(login_url='/user/login')
def edit_book(request, id):
    book = Book.objects.get(id=id)
    form = BookForm(instance=book)
    if request.method == "POST":
        form = BookForm(data=request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect("bookStore:index") 
        
    return render(request, 'edit-book.html', context={
        'form': form, 
        'book': book
    })

@login_required(login_url='/user/login')
def delete_book(request, id):
    Book.objects.get(id=id).delete()
    return redirect('bookStore:index')  

django/djangoLabs/user/views.py
from django.shortcuts import render , redirect
from django.contrib import messages
from django.contrib.auth import login , logout , authenticate
from .forms import LoginForm , SignUpForm


def user_login(request):
    form = LoginForm()
    if request.user.is_authenticated:
        return redirect("BookStore:home-index")

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is None:
            return render(request, "accounts/login.html", {"form": form})
        login(request , user)
        return redirect("BookStore:home-index")
    else:
        return render(request, "accounts/login.html" , {"form": form})


def user_logout(request):
    logout(request)
    return redirect("user:login")


def user_signup(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("user:login")
        else:
            errors = form.errors
            return render(request, "accounts/signup.html" , {"form": form , "errors": errors}) 
    else:
        return render(request, "accounts/signup.html" , {"form": form})

django/djangoLabs/bookStore/templates/book-details.html
{% extends 'main.html' %}

{% block title %}
    Book Store
{% endblock %}

{% block content %}
<div class="card w-50 mx-auto">
    <div class="card-header">
        Book Info.
    </div>
    <div class="card-body">
        <p>ID: {{book.id}}</p>
        <p>Name: {{book.name}}</p>
        <p>Price: {{book.price}}</p>
        <p>Pages: {{book.pages}}</p>
        <p>Author: {{book.author_name}}</p>
        <p>Description: {{book.description}}</p>
        <a href="/bookStore/" class="btn btn-primary">Back to All Books</a>
    </div>
</div>
{% endblock %}

django/djangoLabs/bookStore/templates/create-book.html
{% extends 'main.html' %}
{% block title %} Book Store {% endblock %}
{% block content %}

<form class="form w-50 mx-auto bg-body-secondary border rounded-4 p-5" method="POST">
    {% csrf_token %}
    <h2 class="mb-4">Add new Book</h2>
    <div class="">{{ form.as_p }}</div>
    <input type="submit" class="btn btn-primary mt-5" value="ADD" />
</form>

{% endblock %}

django/djangoLabs/bookStore/templates/edit-book.html
{% extends 'main.html' %}
{% block title %} Book Store {% endblock %}
{% block content %}

<form class="form w-50 mx-auto bg-body-secondary border rounded-4 p-5" action="{% url 'bookStore:edit' book.id %}" method="post">
    {% csrf_token %}
    <h2 class="mb-4">Add new Book</h2>
    <div>{{ form.as_p }}</div>
    <input type="submit" class="btn btn-primary mt-5" value="UPDATE" />
</form>

{% endblock %}

django/djangoLabs/bookStore/templates/index.html
{% extends 'main.html' %}

{% block title %}
    Book Store
{% endblock %}

{% block content %}
<div class="my-4 text-center">
    <a class="btn btn-success" href="{% url 'bookStore:add' %}"> Add New Book</a>
</div>
<table class="table table-primary w-50 text-center mx-auto">
    <thead>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Price</td>
            <td>Description</td>
            <td>Pages</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        {% for book in book_list%}
        <tr>
            <td>{{ book.id }}</td>
            <td>{{ book.name | truncatewords:2  | title }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.author_name }}</td>
            <td>{{ book.pages }}</td>
            <td> 
                <a class="btn btn-primary" href="{% url 'bookStore:show_details' book.id %}"> <i class="bx bx-show-alt" style="color: #fff"></i></a>
                <a class="btn btn-success" href="{% url 'bookStore:edit' book.id %}"> <i class="bx bxs-edit"></i></a>
                <a class="btn btn-danger" href="{% url 'bookStore:delete' book.id %}"> <i class="bx bx-trash"></i></a>
            </td>
        </tr>

        {% empty %}
        <tr class="w-100">
            <td colspan="4" class="text-center w-100">sorry, No Books in list</td>
        </tr>

        {% endfor %}
    </tbody>
</table>
{% endblock %}